name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install go-junit-report
        run: go get -u github.com/jstemmer/go-junit-report

      - name: Run unit tests and generate JUnit XML
        run: |
          go test -json ./... | go-junit-report > unit-tests-report.xml

      - name: Upload unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-report
          path: unit-tests-report.xml

      - name: Run integration tests and generate JUnit XML
        run: |
          go test -v -tags=integration -json ./... | go-junit-report > integration-tests-report.xml

      - name: Upload integration test results
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests-report
          path: integration-tests-report.xml
